// Treasure — shared data + matter-of-fact mocked items across categories.
// Every item carries a category-specific spec sheet, a history of moments,
// and a vector identity (drawn in vectors.jsx, not embedded here).

const CATEGORIES = [
  { id: 'badminton',  name: '羽毛球',     name_en: 'Badminton',   icon: 'racket',  count: 4 },
  { id: 'photo',      name: '摄影',       name_en: 'Photography', icon: 'camera',  count: 6 },
  { id: 'cars',       name: '汽车',       name_en: 'Cars',        icon: 'car',     count: 3, note: '租车记录' },
  { id: 'tech',       name: '电子产品',   name_en: 'Tech',         icon: 'tech',    count: 5 },
];

// Items — small but expressive. Each has: id, category, brand, model,
// nickname (the user's name for it), acquired/parted dates, status,
// 4-color palette derived from the object, hero spec lines, full specs,
// and a timeline of dated moments.

const ITEMS = [
  // ── Badminton ─────────────────────────────────────────────────────────
  {
    id: 'racket-vt-zf2',
    category: 'badminton',
    brand: 'Yonex',
    model: 'Voltric Z-Force II',
    nickname: '黑刃',
    acquired: '2023-04-12',
    status: 'owned',
    location: '北京',
    color_hex: '#1a1a1a',
    palette: ['#0e0e0e', '#c9362f', '#e8e2d4', '#5a5a5a'],
    one_liner: '进攻型 4U · 拉26磅',
    hero_specs: [
      { label: '重量', value: '4U / 83g' },
      { label: '平衡点', value: '294mm' },
      { label: '中杆', value: '硬' },
      { label: '握把', value: 'G5' },
    ],
    specs: {
      '型号': 'Voltric Z-Force II',
      '类型': '进攻型',
      '材质': '高弹性碳素 + Nanometric DR',
      '拉线': 'BG80 Power · 26lbs',
      '握把胶': 'AC102 黑',
      '购入价': '¥1,580',
      '购入渠道': '上海体育用品店',
    },
    history: [
      { date: '2023-04-12', kind: 'acquired',  title: '购入',         note: '在上海徐家汇花了 1580 入手二代' },
      { date: '2023-05-20', kind: 'milestone', title: '第一场比赛',   note: '公司羽毛球赛单打 8 强' },
      { date: '2023-09-03', kind: 'maintain',  title: '换线 BG80',    note: '26 磅，老师傅手工拉的' },
      { date: '2024-02-14', kind: 'mod',       title: '更换握把胶',   note: '换成 AC102 黑色，手感更干' },
      { date: '2024-08-11', kind: 'milestone', title: '杭州友谊赛',   note: '混双 第三名' },
      { date: '2025-11-02', kind: 'maintain',  title: '换线 BG65Ti',  note: '换成更耐用的线，27磅' },
    ],
  },
  {
    id: 'racket-arc11',
    category: 'badminton',
    brand: 'Yonex',
    model: 'Arcsaber 11',
    nickname: '老蓝',
    acquired: '2021-03-08',
    parted: '2024-06-15',
    status: 'parted',
    color_hex: '#1f3a82',
    palette: ['#1f3a82', '#0e1b3d', '#e8e2d4', '#7e94c2'],
    one_liner: '全能型 3U · 已转让',
    hero_specs: [
      { label: '重量', value: '3U / 88g' },
      { label: '平衡点', value: '290mm' },
      { label: '中杆', value: '中等' },
      { label: '握把', value: 'G5' },
    ],
    specs: {
      '型号': 'Arcsaber 11',
      '类型': '全能型',
      '材质': 'Ultra PE Fiber',
      '拉线': 'BG65 · 24lbs',
      '购入价': '¥1,200',
      '出手价': '¥600',
      '出手原因': '换 Z-Force II',
    },
    history: [
      { date: '2021-03-08', kind: 'acquired',  title: '购入',         note: '入门进阶第一支正经拍' },
      { date: '2021-07-22', kind: 'milestone', title: '第一次扣杀得分', note: '比赛中第一次扣杀直接得分' },
      { date: '2022-11-04', kind: 'maintain',  title: '断线',         note: '高远球时断线，换 BG65' },
      { date: '2024-06-15', kind: 'parted',    title: '转让给同事',   note: '600 元转让给小李' },
    ],
  },
  {
    id: 'racket-astrox-99',
    category: 'badminton',
    brand: 'Yonex',
    model: 'Astrox 99 Pro',
    nickname: '橘子',
    acquired: '2024-09-21',
    status: 'owned',
    color_hex: '#d97757',
    palette: ['#d97757', '#8a3a1f', '#f6f0e6', '#231e1a'],
    one_liner: '进攻型 4U · 桃田款',
    hero_specs: [
      { label: '重量', value: '4U / 83g' },
      { label: '平衡点', value: '305mm' },
      { label: '中杆', value: '极硬' },
      { label: '握把', value: 'G5' },
    ],
    specs: {
      '型号': 'Astrox 99 Pro',
      '类型': '进攻型',
      '配色': 'Cherry Sunburst',
      '拉线': 'BG66UM · 27lbs',
      '购入价': '¥1,890',
      '购入渠道': '京东自营',
    },
    history: [
      { date: '2024-09-21', kind: 'acquired',  title: '购入',         note: '看了桃田比赛太眼馋' },
      { date: '2024-10-08', kind: 'maintain',  title: '首次拉线',     note: 'BG66UM 27磅' },
      { date: '2025-03-15', kind: 'milestone', title: '俱乐部联赛',   note: '团体赛第二名' },
    ],
  },
  {
    id: 'shoes-shb65',
    category: 'badminton',
    brand: 'Yonex',
    model: 'Power Cushion 65 Z3',
    nickname: '小白鞋',
    acquired: '2024-04-02',
    status: 'owned',
    color_hex: '#f5f1e8',
    palette: ['#f5f1e8', '#1a1a1a', '#c9362f', '#7a7a7a'],
    one_liner: '羽毛球鞋 · 41码',
    hero_specs: [
      { label: '尺码', value: 'EU 41' },
      { label: '重量', value: '约 310g' },
      { label: '科技', value: 'Power Cushion+' },
      { label: '场地', value: '室内木地板' },
    ],
    specs: {
      '型号': 'SHB 65 Z3',
      '尺码': 'EU 41 / 26.5cm',
      '配色': '白红',
      '购入价': '¥980',
    },
    history: [
      { date: '2024-04-02', kind: 'acquired',  title: '购入',         note: '日亚海淘' },
      { date: '2024-12-20', kind: 'maintain',  title: '更换鞋垫',     note: '原装鞋垫塌了，换了一副' },
    ],
  },

  // ── Photography ───────────────────────────────────────────────────────
  {
    id: 'cam-fuji-xt5',
    category: 'photo',
    brand: 'Fujifilm',
    model: 'X-T5',
    nickname: '小富士',
    acquired: '2023-02-14',
    status: 'owned',
    color_hex: '#1a1a1a',
    palette: ['#1a1a1a', '#3a3530', '#d8d2c4', '#8a8378'],
    one_liner: 'APS-C 旗舰 · 4020万像素',
    hero_specs: [
      { label: '传感器', value: 'X-Trans CMOS 5' },
      { label: '像素', value: '40.2 MP' },
      { label: '机身防抖', value: '7档 IBIS' },
      { label: '快门寿命', value: '50万次' },
    ],
    specs: {
      '型号': 'X-T5 Black',
      '传感器': 'APS-C X-Trans CMOS 5 HR',
      '处理器': 'X-Processor 5',
      '取景器': '0.5英寸 369万像素 OLED',
      '视频': '6.2K 30p / 4K 60p',
      '续航': 'CIPA 580 张',
      '购入价': '¥12,500（机身）',
      '购入渠道': '富士官方天猫店',
    },
    history: [
      { date: '2023-02-14', kind: 'acquired',  title: '机身购入',     note: '首发后等了三个月才买到' },
      { date: '2023-03-20', kind: 'mod',       title: '配 23mm F2',   note: '人文挂机镜头' },
      { date: '2023-08-15', kind: 'milestone', title: '京都之行',     note: '拍了 1200 张，胶片模拟太香了' },
      { date: '2024-05-01', kind: 'mod',       title: '加 56mm F1.2', note: '拍人像专用' },
      { date: '2024-10-12', kind: 'maintain',  title: '传感器除尘',   note: '官方上海店清理' },
      { date: '2025-09-08', kind: 'milestone', title: '冰岛环线',     note: '极光夜，长曝光神器' },
    ],
  },
  {
    id: 'lens-23f2',
    category: 'photo',
    brand: 'Fujifilm',
    model: 'XF 23mm F2 R WR',
    nickname: '人文头',
    acquired: '2023-03-20',
    status: 'owned',
    color_hex: '#222',
    palette: ['#1a1a1a', '#5a5a5a', '#d8d2c4', '#8a8378'],
    one_liner: '等效 35mm · F2 定焦',
    hero_specs: [
      { label: '焦距', value: '23mm (35mm e)' },
      { label: '光圈', value: 'F2 - F16' },
      { label: '最近对焦', value: '22cm' },
      { label: '滤镜', value: 'Φ43mm' },
    ],
    specs: {
      '型号': 'XF 23mm F2 R WR',
      '镜片结构': '10片6组（2片非球面）',
      '光圈叶片': '9片圆形',
      '重量': '180g',
      '防尘防滴': '是',
      '购入价': '¥2,800',
    },
    history: [
      { date: '2023-03-20', kind: 'acquired',  title: '购入',         note: '配 X-T5 一起的' },
      { date: '2024-03-08', kind: 'maintain',  title: '镜头进灰',     note: '不影响成像' },
    ],
  },
  {
    id: 'lens-56f12',
    category: 'photo',
    brand: 'Fujifilm',
    model: 'XF 56mm F1.2 R WR',
    nickname: '大眼睛',
    acquired: '2024-05-01',
    status: 'owned',
    color_hex: '#1a1a1a',
    palette: ['#1a1a1a', '#3a3530', '#e8e2d4', '#7a7570'],
    one_liner: '人像头 · 等效 85mm F1.2',
    hero_specs: [
      { label: '焦距', value: '56mm (85mm e)' },
      { label: '光圈', value: 'F1.2 - F16' },
      { label: '最近对焦', value: '50cm' },
      { label: '滤镜', value: 'Φ67mm' },
    ],
    specs: {
      '型号': 'XF 56mm F1.2 R WR (二代)',
      '镜片结构': '13片8组',
      '光圈叶片': '11片圆形',
      '重量': '445g',
      '购入价': '¥7,800',
    },
    history: [
      { date: '2024-05-01', kind: 'acquired', title: '购入',     note: '京东活动 7800 拿下' },
      { date: '2024-07-04', kind: 'milestone', title: '第一次拍婚礼', note: '帮朋友拍婚礼，全场用它' },
    ],
  },
  {
    id: 'cam-ricoh-gr3',
    category: 'photo',
    brand: 'Ricoh',
    model: 'GR III',
    nickname: '小石头',
    acquired: '2022-08-19',
    status: 'owned',
    color_hex: '#1a1a1a',
    palette: ['#1a1a1a', '#2a2a2a', '#d8d2c4', '#7a7a7a'],
    one_liner: 'APS-C 街拍口袋机',
    hero_specs: [
      { label: '传感器', value: 'APS-C CMOS' },
      { label: '镜头', value: '18.3mm F2.8' },
      { label: '像素', value: '24.2 MP' },
      { label: '重量', value: '257g' },
    ],
    specs: {
      '型号': 'GR III',
      '镜头': 'GR LENS 18.3mm F2.8（等效28mm）',
      '防抖': '三轴机身防抖',
      '尺寸': '109.4 × 61.9 × 33.2 mm',
      '购入价': '¥6,200',
      '购入渠道': '日本中古回购店',
    },
    history: [
      { date: '2022-08-19', kind: 'acquired',  title: '日本中古入',    note: '东京中野店买的二手' },
      { date: '2023-06-01', kind: 'maintain',  title: '镜头进灰返厂',  note: '深圳维修点 800 元' },
      { date: '2024-01-15', kind: 'milestone', title: '陪我走完曼谷',  note: '7天 600 张街拍' },
    ],
  },
  {
    id: 'cam-leica-m6',
    category: 'photo',
    brand: 'Leica',
    model: 'M6',
    nickname: '老玩具',
    acquired: '2024-11-30',
    status: 'owned',
    color_hex: '#2a2a2a',
    palette: ['#2a2a2a', '#0a0a0a', '#d4cdb8', '#a89c7a'],
    one_liner: '胶片旁轴 · 1984 年制',
    hero_specs: [
      { label: '类型', value: '35mm 旁轴' },
      { label: '快门', value: '1s - 1/1000s' },
      { label: '取景器', value: '0.72x' },
      { label: '生产年份', value: '1984' },
    ],
    specs: {
      '型号': 'Leica M6 (Classic)',
      '序列号': '167xxxx',
      '配镜': 'Summicron 50mm F2 v4',
      '产地': '德国韦茨拉尔',
      '购入价': '¥38,000（中古）',
      '购入渠道': '北京中古店',
    },
    history: [
      { date: '2024-11-30', kind: 'acquired', title: '购入',     note: '生日礼物 给自己' },
      { date: '2025-01-05', kind: 'milestone', title: '拍完第一卷', note: 'Portra 400 · 北京胡同' },
      { date: '2025-04-10', kind: 'maintain',  title: '快门 CLA', note: '北京 fix-it 老师傅，2400元' },
    ],
  },
  {
    id: 'tripod-rrs',
    category: 'photo',
    brand: 'Really Right Stuff',
    model: 'TVC-24L',
    nickname: '稳如山',
    acquired: '2023-12-08',
    status: 'owned',
    color_hex: '#1a1a1a',
    palette: ['#1a1a1a', '#2a2a2a', '#c4b89c', '#7a6f56'],
    one_liner: '碳纤维三脚架 · 4节',
    hero_specs: [
      { label: '材质', value: '碳纤维' },
      { label: '最高', value: '163cm' },
      { label: '收纳', value: '53cm' },
      { label: '承重', value: '15.9kg' },
    ],
    specs: {
      '型号': 'TVC-24L Long',
      '管节': '4节',
      '管径': '28.6mm',
      '重量': '1.6kg',
      '云台': '配 BH-40 球台',
      '购入价': '¥9,800',
    },
    history: [
      { date: '2023-12-08', kind: 'acquired', title: '购入',     note: '冰岛行准备' },
      { date: '2024-02-08', kind: 'milestone', title: '拍极光', note: '-22℃ 户外 4 小时' },
    ],
  },

  // ── Cars (rentals) ─────────────────────────────────────────────────────
  {
    id: 'car-bmw-m2',
    category: 'cars',
    brand: 'BMW',
    model: 'M2 Competition',
    nickname: '小钢炮',
    acquired: '2024-05-12',
    parted: '2024-05-15',
    status: 'rented',
    color_hex: '#1a1a1a',
    palette: ['#1a1a1a', '#2a2a2a', '#c9362f', '#a8a8a8'],
    one_liner: '租赁 3 天 · 1240 公里',
    hero_specs: [
      { label: '动力', value: 'L6 3.0T' },
      { label: '马力', value: '410 PS' },
      { label: '0-100', value: '4.4 s' },
      { label: '驱动', value: '后驱' },
    ],
    specs: {
      '车型': 'M2 Competition',
      '车牌': '京 A 79***',
      '颜色': '矿石黑',
      '租赁公司': 'TripCar',
      '租赁费用': '¥4,800（3天）',
      '里程': '1240 km',
      '路线': '北京 → 张家口 → 草原天路',
    },
    history: [
      { date: '2024-05-12', kind: 'acquired',  title: '提车',         note: '北京机场店 · 满油提车' },
      { date: '2024-05-13', kind: 'milestone', title: '草原天路',     note: '在 G6 高速跑了 220km/h' },
      { date: '2024-05-14', kind: 'milestone', title: '张北野餐',     note: '日落时拍了一组车的照片' },
      { date: '2024-05-15', kind: 'parted',    title: '还车',         note: '完美还车 没有刮蹭' },
    ],
  },
  {
    id: 'car-911',
    category: 'cars',
    brand: 'Porsche',
    model: '911 Carrera S (992)',
    nickname: '梦中情车',
    acquired: '2025-07-04',
    parted: '2025-07-06',
    status: 'rented',
    color_hex: '#dcd8d0',
    palette: ['#dcd8d0', '#a8a39a', '#1a1a1a', '#d97757'],
    one_liner: '租赁 2 天 · 加州海岸',
    hero_specs: [
      { label: '动力', value: 'F6 3.0T 双涡轮' },
      { label: '马力', value: '450 PS' },
      { label: '0-100', value: '3.7 s' },
      { label: '配置', value: 'PDK 8速' },
    ],
    specs: {
      '车型': '911 Carrera S 992.1',
      '颜色': 'Crayon Grey',
      '租赁公司': 'Hertz Dream Cars',
      '租赁费用': '$1,650（2天）',
      '里程': '480 mi',
      '路线': 'San Francisco → Big Sur → Carmel',
    },
    history: [
      { date: '2025-07-04', kind: 'acquired',  title: 'SFO 提车',     note: '金门大桥日落开过' },
      { date: '2025-07-05', kind: 'milestone', title: '1号公路',      note: 'Big Sur 海岸 280 公里' },
      { date: '2025-07-06', kind: 'parted',    title: '还车',         note: '依依不舍' },
    ],
  },
  {
    id: 'car-defender',
    category: 'cars',
    brand: 'Land Rover',
    model: 'Defender 110',
    nickname: '大方块',
    acquired: '2024-09-28',
    parted: '2024-10-04',
    status: 'rented',
    color_hex: '#3a4a3a',
    palette: ['#3a4a3a', '#1a2a1a', '#c4b89c', '#d8d2c4'],
    one_liner: '租赁 7 天 · 川西环线',
    hero_specs: [
      { label: '动力', value: 'L6 3.0T 轻混' },
      { label: '马力', value: '400 PS' },
      { label: '驱动', value: '四驱' },
      { label: '涉水', value: '900mm' },
    ],
    specs: {
      '车型': 'Defender 110 P400',
      '颜色': 'Pangea Green',
      '租赁公司': '成都自由行',
      '租赁费用': '¥9,800（7天）',
      '里程': '2380 km',
      '路线': '成都 → 稻城亚丁 → 新都桥 → 成都',
    },
    history: [
      { date: '2024-09-28', kind: 'acquired',  title: '成都提车',     note: '满油 + 全险' },
      { date: '2024-09-30', kind: 'milestone', title: '稻城亚丁',     note: '4500m 牛奶海' },
      { date: '2024-10-02', kind: 'milestone', title: '新都桥',       note: '摄影天堂 拍了一整天' },
      { date: '2024-10-04', kind: 'parted',    title: '还车',         note: '右后门一道小划痕 800元' },
    ],
  },

  // ── Tech ───────────────────────────────────────────────────────────────
  {
    id: 'tech-mbp',
    category: 'tech',
    brand: 'Apple',
    model: 'MacBook Pro 14" M4 Pro',
    nickname: '主力机',
    acquired: '2024-11-20',
    status: 'owned',
    color_hex: '#3a3a3c',
    palette: ['#3a3a3c', '#1a1a1c', '#d8d2c4', '#8a8378'],
    one_liner: '工作机 · 24G/1T',
    hero_specs: [
      { label: 'CPU', value: 'M4 Pro 12核' },
      { label: '内存', value: '24 GB' },
      { label: '存储', value: '1 TB' },
      { label: '屏幕', value: '14.2" XDR 120Hz' },
    ],
    specs: {
      '型号': 'MacBook Pro 14"',
      '芯片': 'Apple M4 Pro 12CPU/16GPU',
      '内存': '24 GB Unified',
      '存储': '1 TB SSD',
      '颜色': 'Space Black',
      '购入价': '¥18,499',
      '购入渠道': '教育优惠',
    },
    history: [
      { date: '2024-11-20', kind: 'acquired',  title: '购入',         note: '替换服役 4 年的 M1' },
      { date: '2025-02-10', kind: 'mod',       title: '配 Studio Display', note: '外接 27 寸屏' },
    ],
  },
  {
    id: 'tech-airpods',
    category: 'tech',
    brand: 'Apple',
    model: 'AirPods Pro 2',
    nickname: '耳朵',
    acquired: '2023-09-22',
    status: 'owned',
    color_hex: '#f6f4ef',
    palette: ['#f6f4ef', '#dcd8d0', '#1a1a1a', '#a8a39a'],
    one_liner: 'TWS 耳机 · USB-C',
    hero_specs: [
      { label: '芯片', value: 'H2' },
      { label: '续航', value: '6h + 30h 盒' },
      { label: '降噪', value: '主动降噪' },
      { label: '接口', value: 'USB-C' },
    ],
    specs: {
      '型号': 'AirPods Pro (2nd gen, USB-C)',
      '购入价': '¥1,899',
      '购入渠道': 'Apple Store 三里屯',
    },
    history: [
      { date: '2023-09-22', kind: 'acquired', title: '购入',     note: '首发当天去三里屯' },
      { date: '2024-08-04', kind: 'maintain', title: '换右耳',   note: '充电仓里掉出来摔了，换右耳' },
    ],
  },
  {
    id: 'tech-kindle',
    category: 'tech',
    brand: 'Kindle',
    model: 'Oasis 3',
    nickname: '夜读',
    acquired: '2020-06-12',
    status: 'owned',
    color_hex: '#5a5854',
    palette: ['#5a5854', '#3a3835', '#d4cdb8', '#a8a39a'],
    one_liner: '电纸书 · 7寸 32G',
    hero_specs: [
      { label: '屏幕', value: '7" 300ppi' },
      { label: '存储', value: '32 GB' },
      { label: '防水', value: 'IPX8' },
      { label: '前光', value: '可调色温' },
    ],
    specs: {
      '型号': 'Kindle Oasis 3 (10代)',
      '颜色': '石墨灰',
      '购入价': '¥2,399',
      '购入渠道': '亚马逊海外购',
    },
    history: [
      { date: '2020-06-12', kind: 'acquired', title: '购入',     note: '亚马逊海外购' },
      { date: '2022-12-10', kind: 'maintain', title: '换电池',   note: '续航明显下降' },
    ],
  },
  {
    id: 'tech-watch',
    category: 'tech',
    brand: 'Apple',
    model: 'Watch Ultra 2',
    nickname: '大表盘',
    acquired: '2024-03-15',
    status: 'owned',
    color_hex: '#7a7165',
    palette: ['#7a7165', '#3a3530', '#c4b89c', '#d8d2c4'],
    one_liner: '钛金属 · 49mm',
    hero_specs: [
      { label: '材质', value: '钛金属' },
      { label: '尺寸', value: '49 mm' },
      { label: '续航', value: '36h / 72h 省电' },
      { label: '防水', value: '100m' },
    ],
    specs: {
      '型号': 'Apple Watch Ultra 2',
      '表带': 'Trail Loop 橙色',
      '购入价': '¥6,499',
    },
    history: [
      { date: '2024-03-15', kind: 'acquired', title: '购入',     note: '替换 SE 一代' },
      { date: '2024-08-11', kind: 'milestone', title: '半马',   note: '记录第一次半程马拉松' },
    ],
  },
  {
    id: 'tech-ipad',
    category: 'tech',
    brand: 'Apple',
    model: 'iPad Pro 11" M4',
    nickname: '画板',
    acquired: '2024-06-08',
    status: 'owned',
    color_hex: '#3a3a3c',
    palette: ['#3a3a3c', '#1a1a1c', '#d8d2c4', '#a8a39a'],
    one_liner: 'OLED · 256G',
    hero_specs: [
      { label: '芯片', value: 'M4' },
      { label: '屏幕', value: '11" OLED 120Hz' },
      { label: '存储', value: '256 GB' },
      { label: '配件', value: 'Apple Pencil Pro' },
    ],
    specs: {
      '型号': 'iPad Pro 11" M4 Wi-Fi',
      '颜色': '深空黑',
      '购入价': '¥8,999',
    },
    history: [
      { date: '2024-06-08', kind: 'acquired', title: '购入',     note: '首发 + 教育优惠' },
      { date: '2024-06-20', kind: 'mod',     title: '配 Pencil Pro', note: '画图 + 笔记' },
    ],
  },
];

// Helpers
const itemsByCategory = (cid) => ITEMS.filter((i) => i.category === cid);
const itemById = (id) => ITEMS.find((i) => i.id === id);
const fmtDate = (s) => {
  if (!s) return '';
  const [y, m, d] = s.split('-');
  return `${y}.${m}.${d}`;
};
const fmtDateShort = (s) => {
  if (!s) return '';
  const [y, m, d] = s.split('-');
  return `${m}/${d}`;
};
const fmtYear = (s) => s ? s.split('-')[0] : '';

// Compute "owned for" duration in years/months from acquired→(parted|today).
const ownedFor = (item) => {
  if (!item.acquired) return '';
  const start = new Date(item.acquired);
  const end = item.parted ? new Date(item.parted) : new Date('2026-05-06');
  const months = Math.max(0, Math.round((end - start) / (1000 * 60 * 60 * 24 * 30.44)));
  if (months < 12) return `${months} 个月`;
  const y = Math.floor(months / 12), m = months % 12;
  return m ? `${y} 年 ${m} 个月` : `${y} 年`;
};

Object.assign(window, {
  CATEGORIES, ITEMS, itemsByCategory, itemById,
  fmtDate, fmtDateShort, fmtYear, ownedFor,
});
